sudo: false
language: node_js
os: osx

node_js:
  - "6"
  - "7"

before_install:
  - brew install sdl2

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  - npm test
