sudo: false
language: node_js
os: osx
osx_image: xcode8

env:
  - CXX=g++-4.8

node_js:
  - "8"

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install

script:
  # Output useful info for debugging
  - $CXX --version
  - node --version
  - npm --version
  - npm test
